[project]
name = "timelocked-wallet"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"

[contracts.smart-claimnt]
path = "contracts/smart-claimnt.clar"

[contracts.timelocked-wallet]
path = "contracts/timelocked-wallet.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
