[project]
name = "sip010-ft"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"

[contracts.dino-coin]
path = "contracts/dino-coin.clar"
depends_on = ["sip010-ft-trait"]

[contracts.sip010-ft-trait]
path = "contracts/sip010-ft-trait.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
